Repository oracle-devrel/technology-engineering, pull requests merged in 2023-09, with the labels that each got.

#369 OIC Recipes
  app-dev/app-integration-and-automation/reusable-assets-cloud/README.md
Labels: OCA Verified

#393 Red Hat OpenShift on Oracle Cloud VMware Solution
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/README.md
Labels: OCA Verified

#388 Essbase SDD update
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/hyperion-essbase/essbase-solution-definition/files/essbase-solution-definition.docx
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/hyperion-essbase/essbase-solution-definition/files/essbase-solution-definition.md
Labels: OCA Required

#397 Daniel&dev2
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/README.md
Labels: OCA Verified

#401 Uschwinn performance
  data-platform/core-converged-db/db-performance/README.md
  data-platform/core-converged-db/db-performance/performancehub/README.md
  data-platform/core-converged-db/db-performance/performancehub/dbmsperf_1.sql
  data-platform/core-converged-db/db-performance/performancehub/dbmsperf_def.sql
  data-platform/core-converged-db/db-performance/performancehub/perfhubscript.sql
Labels: OCA Verified

#400 Updated readme
  data-platform/analytical-data-platform-lakehouse/README.md
Labels: OCA Required

#394 Hyperion landing page
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/hyperion-essbase/README.md
Labels: OCA Required

#385 Update README.md
  manageability-and-operations/observability-and-manageability/Logging/README.md
Labels: OCA Required

#384 Update README.md
  manageability-and-operations/observability-and-manageability/README.md
Labels: OCA Required

#402 Lift multicloud publications
  cloud-infrastructure/multicloud/azure-interconnect/README.md
  cloud-infrastructure/multicloud/federation-azure/README.md
  cloud-infrastructure/multicloud/integrate-okta-iam/README.md
Labels: OCA Verified

#405 wcc migration filename modified
  app-dev/content-management/README.md
  app-dev/content-management/ocm-files/WebCenter_Content_Migration_to_OCI.pdf
Labels: OCA Verified

#361 Add access-extension-notification scheduled task sample for OIG
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-extension-notification/LICENSE
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-extension-notification/README.md
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-extension-notification/files/Access_Extension_Notification.xml
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-extension-notification/files/Access_Extension_Template.xml
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-extension-notification/files/EXTEND_ACCESS.sql
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-extension-notification/files/src/com/oracle/sample/AccessExtensionNotification.java
Labels: OCA Verified

#362 Add extend-access-ws web service sample for OIG/WebLogic
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/LICENSE
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/README.md
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/files/WebContent/META-INF/MANIFEST.MF
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/files/WebContent/WEB-INF/ExtendAccessWSv1Service/com/oracle/samplews/deploy.wsdd
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/files/WebContent/WEB-INF/ExtendAccessWSv1Service/com/oracle/samplews/undeploy.wsdd
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/files/WebContent/WEB-INF/web.xml
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/files/WebContent/wsdl/ExtendAccessWSv1.wsdl
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/files/extendaccessws.properties
  security/identity-and-access-management/oracle-identity-governance/webservice-samples/extend-access-ws/files/src/com/oracle/samplews/ExtendAccessWSv1.java
Labels: OCA Verified

#411 Update IAM team README.md
  security/identity-and-access-management/README.md
Labels: OCA Verified

#398 Added SD template new 2
  others/customer-documentation/solution-definition-complete/README.md
  others/customer-documentation/solution-definition-complete/files/images/MultiADDR-DeploymentDiagram-V2.pdf
  others/customer-documentation/solution-definition-complete/files/solution-definition.md
  others/customer-documentation/solution-definition-mandatory/README.md
  others/customer-documentation/solution-definition-mandatory/files/images/MultiADDR-DeploymentDiagram-V2.pdf
  others/customer-documentation/solution-definition-mandatory/files/solution-definition_mandatory.md
Labels: OCA Verified, new, test-team

#169 First Release
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/LICENSE
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/README.md
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/images/DatasafetoOCILoggingArchitecture.jpg
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/buckets.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/container_repository.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/datasources.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/function/oci-datasafe-audit-to-logging/func.py
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/function/oci-datasafe-audit-to-logging/func.yaml
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/function/oci-datasafe-audit-to-logging/requirements.txt
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/function_invoke.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/function_prep.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/functions.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/locals.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/logging.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/main.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/modules/network/locals.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/modules/network/main.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/modules/network/output.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/modules/network/tags.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/modules/network/variables.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/policies.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/provider.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/schedule.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/schema.yaml
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/tags.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/terraform.tfvars.sample
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/terraform/variables.tf
  security/security-design/fn-datasafe-dbaudit-to-oci-logging/zip/fn-datasafe-dbaudit-to-oci-logging.zip
Labels: OCA Verified

#418 Adding new CN homepage
  app-dev/cloud-native/README.md
Labels: OCA Verified

#409 Food beverage assets
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/food-beverage/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/food-beverage/food-beverage-discovery-questionnaire/LICENSE
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/food-beverage/food-beverage-discovery-questionnaire/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/food-beverage/food-beverage-discovery-questionnaire/files/food-beverage-discovery-questionnaire.xlsx
Labels: OCA Verified

#406 Rgbu disc quest delta
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail-gbu/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail-gbu/rgbu-discovery-questionnaire/LICENSE
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail-gbu/rgbu-discovery-questionnaire/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail-gbu/rgbu-discovery-questionnaire/files/retail-discovery-questionnaire.xlsx
Labels: OCA Verified

#407 Construction engineering discovery questionnaire
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/construction-engineering-discovery-questionnaire/LICENSE
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/construction-engineering-discovery-questionnaire/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/construction-engineering-discovery-questionnaire/files/construction-engineering-discovery-questionnaire.xlsx
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/files/images/primavera-logical-arch.drawio
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/files/images/primavera-logical-arch.png
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/files/images/primavera-physical-arch-1ad.drawio
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/files/images/primavera-physical-arch-1ad.png
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/files/images/primavera-physical-arch-2region.drawio
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/files/images/primavera-physical-arch-multiad.drawio
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/files/primavera-solution-definition.docx
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/construction-engineering/primavera-solution-definition/files/primavera-solution-definition.md
Labels: OCA Verified

#426 Updating Data Transforms readme
  data-platform/data-integration/data transforms/README.md
Labels: OCA Verified

#419 public-assets
  app-dev/app-integration-and-automation/oci-api-management/oic-with-oci-api-gtw/OICOCIAPIGateway_Patterns_0.1.pdf
  app-dev/app-integration-and-automation/oci-api-management/oic-with-oci-api-gtw/README.md
  app-dev/app-integration-and-automation/oracle-integration-cloud/03-oic-outbound-ip-address/OICOutboundIPAddress_1.0.pdf
  app-dev/app-integration-and-automation/oracle-integration-cloud/03-oic-outbound-ip-address/README.md
  app-dev/app-integration-and-automation/reusable-assets-cloud/event-management/Integration_EventManagement_v1.0.pdf
  app-dev/app-integration-and-automation/reusable-assets-cloud/event-management/README.md
  app-dev/app-integration-and-automation/reusable-assets-cloud/oic-fan-out-pattern/PatternDefinition_MDM-to-OIC-Fan-Out_v1_0.pdf
  app-dev/app-integration-and-automation/reusable-assets-cloud/oic-fan-out-pattern/README.md
Labels: OCA Verified

#439 Changing folder names
  data-platform/data-integration/oci-data-catalog/README.md
  data-platform/data-integration/oci-data-integration/README.md
  data-platform/data-integration/oci-goldengate/README.md
  data-platform/data-integration/oracle-data-transforms/README.md
Labels: OCA Verified

#440 added CCC link
  app-dev/content-management/README.md
Labels: OCA Verified

#443 NewAsset
  app-dev/app-integration-and-automation/shared-assets/README.md
Labels: OCA Verified

#424 Update README.md
  manageability-and-operations/observability-and-manageability/README.md
  manageability-and-operations/observability-and-manageability/oci-monitoring/README.md
Labels: OCA Verified

#437 FSGBU questionnaire
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/financial-services/LICENSE
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/financial-services/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/financial-services/financial-services-discovery-questionnaire/LICENSE
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/financial-services/financial-services-discovery-questionnaire/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/financial-services/financial-services-discovery-questionnaire/files/financial-services-discovery-questionnaire.xlsx
Labels: OCA Verified

#427 gbu renamed to oracle industry
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-discovery-questionnaire/LICENSE
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-discovery-questionnaire/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-discovery-questionnaire/files/retail-discovery-questionnaire.xlsx
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-solution-definition/LICENSE
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-solution-definition/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-solution-definition/files/images/retail-logical-arch.drawio
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-solution-definition/files/images/retail-logical-arch.drawio.png
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-solution-definition/files/images/retail-physical-arch.drawio
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-solution-definition/files/images/retail-physical-arch.drawio.png
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/retail-solution-definition/files/retail-solution-definition.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/rms-decision-tree/LICENSE
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/rms-decision-tree/README.md
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail/rms-decision-tree/files/rms-decision-tree.html
Labels: OCA Verified

#425 Siebel word sd
  cloud-architecture/oracle-apps-hyperion-siebel-gbu/siebel/siebel-solution-definition/files/Siebel-Solution-Definition.docx
Labels: OCA Verified

#445 minor update review.
  landing-zones/commons/select_your_solution.pdf
  landing-zones/standard_landing_zones/standard_landing_zones.md
Labels: OCA Verified

#444 Update README.md
  cloud-infrastructure/storage/block-storage/README.md
Labels: OCA Verified

#448 AI-videos
  app-dev/ai-cloud-services/ai-language/README.md
  app-dev/ai-cloud-services/ai-speech/README.md
  app-dev/ai-cloud-services/ai-vision/README.md
  app-dev/ai-cloud-services/document-understanding/README.md
  app-dev/generative-ai-services-and-cohere/README.md
Labels: OCA Verified

#86 lift-analytics-Maps using Json files
  data-platform/analytics/oac-map-extensions/LICENSE
  data-platform/analytics/oac-map-extensions/README.md
  data-platform/analytics/oac-map-extensions/THIRD_PARTY_LICENSES
  data-platform/analytics/oac-map-extensions/files/images/Figure 1.png
  data-platform/analytics/oac-map-extensions/files/images/Figure 2.png
  data-platform/analytics/oac-map-extensions/files/images/Figure 3.png
  data-platform/analytics/oac-map-extensions/files/images/Figure 4.png
  data-platform/analytics/oac-map-extensions/files/images/Figure 5.png
  data-platform/analytics/oac-map-extensions/files/oac-map-extensions.md
Labels: OCA Verified

#453 Faisal
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/discovery-questionnaire/README.md
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/discovery-questionnaire/files/ocvs-discovery-questionnaire.xlsx
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/README.md
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/OCVS_Migration_SD_Template_v1.1.md
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/HCXmigrationarchitecture.png
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/Landing_zone.png
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/bmdensioperformance.jpg
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/fc.png
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/futurestatearchitecture.jpg
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/futurestatearchitecturedr.jpg
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/futurestatearchitecturemigration.png
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/landing-zone.jpg
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/logicalfuturestatearchitecture.jpg
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/net_overview.png
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/ociresponsibilitymatrix.JPG
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/ociresponsibilitymatrix.png
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/ocvs-overview.png
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/ocvsresponsibilitymatrix.JPG
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/physicalarchitecture.jpg
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/sample-currentstatearchitecture.jpg
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/veeam.png
  cloud-infrastructure/vmware-solutions/oracle-cloud-vmware-solution/vmware-migration-solution-definition/files/images/vpn.png
Labels: OCA Required

#454 updated readme.md
  data-platform/analytical-data-platform-lakehouse/README.md
Labels: OCA Verified

#447 Adding folder for ODI and update OCI DI with new links
  data-platform/data-integration/oci-data-integration/README.md
  data-platform/data-integration/oracle-data-integrator/README.md
Labels: OCA Verified

#455 updated readme.md
  data-platform/analytical-data-platform-lakehouse/README.md
Labels: OCA Verified

#458 Lzf.2023.09.3
  landing-zones/commons/lz_solution_definition.md
  landing-zones/commons/user_identity_management.md
  landing-zones/standard_landing_zones/cis_lz_v2/cis_landing_zone.drawio
  landing-zones/standard_landing_zones/cis_lz_v2/cis_landing_zone_v2.md
  landing-zones/tailored_landing_zones/tailored_landing_zones.md
Labels: OCA Required

#421 Fn datasafe to oci logging2
  security/security-design/README.md
Labels: OCA Verified

#429 Add access-termination-notification scheduled task sample for OIG
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-termination-notification/LICENSE
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-termination-notification/README.md
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-termination-notification/files/Access_Termination_Notification.xml
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-termination-notification/files/Access_Termination_Template.xml
  security/identity-and-access-management/oracle-identity-governance/scheduled-task-samples/access-termination-notification/files/src/com/oracle/sample/AccessTerminationNotification.java
Labels: OCA Verified

#462 Changed title of Generative AI page
  ai-and-app-modernisation/generative-ai-services-and-cohere/README.md
Labels: OCA Verified

#461 Update README.md
  manageability-and-operations/observability-and-manageability/README.md
Labels: OCA Verified

#464 updated ai services content
  ai-and-app-modernisation/ai-cloud-services/ai-language/README.md
  ai-and-app-modernisation/ai-cloud-services/ai-speech/README.md
  ai-and-app-modernisation/ai-cloud-services/ai-vision/README.md
  ai-and-app-modernisation/ai-cloud-services/document-understanding/README.md
Labels: OCA Verified

#466 jj moved Gen AI under AI Services
  ai-and-app-modernisation/README.md
  ai-and-app-modernisation/ai-services/README.md
  ai-and-app-modernisation/ai-services/ai-document-understanding/README.md
  ai-and-app-modernisation/ai-services/ai-language/README.md
  ai-and-app-modernisation/ai-services/ai-speech/README.md
  ai-and-app-modernisation/ai-services/ai-vision/README.md
  ai-and-app-modernisation/ai-services/generative-ai-services-and-cohere/README.md
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/LICENSE
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/README.md
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/templates/LICENSE
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/templates/README.md
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/templates/concierge-template/ConciergeTemplate 23.04.pdf
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/templates/concierge-template/Concierge_Template(23.04).zip
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/templates/concierge-template/LICENSE
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/templates/concierge-template/Sample_QnA.pdf
  ai-and-app-modernisation/ai-services/oracle-digital-assistant/templates/concierge-template/web.zip
Labels: OCA Verified

#467 Update README.md
  ai-and-app-modernisation/README.md
Labels: OCA Verified

#468 cloud_coaching add
  manageability-and-operations/operations-advisory/README.md
Labels: OCA Verified

#457 Update README.md
  ai-and-app-modernisation/README.md
Labels: OCA Verified

#463 moving everything up one folder in the hierarchy
  app-dev/README.md
Labels: OCA Verified

#374 Integrations on SQL Tools README.md
  data-platform/data-development/sql-tools/README.md
Labels: OCA Verified

#469 Update README.md
  ai-and-app-modernisation/ai-services/ai-language/README.md
Labels: OCA Verified

#441 Update README.md
  cloud-infrastructure/infrastructure-security/iam/README.md
Labels: OCA Verified

#471 Update README.md and add change hostname of VM
  cloud-infrastructure/compute-including-hpc/compute-hardware/README.md
Labels: OCA Verified

#473 Add files via upload
  cloud-architecture/custom-apps-and-consolidation/weblogic/weblogic-for-oke/files/weblogic_for_oke_acme_architecture.pdf
Labels: OCA Verified
